In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("C:\\Users\\apadh\\OneDrive\\Desktop\\project\\social_media\\social_media_usage_mental_health.csv")

In [3]:
df.head(3)

,user_id,age,country,platform,daily_usage_minutes,content_type,engagement_score,mental_fatigue_level,date
0,1,54,UK,Instagram,253,Reels,0.79,9,2023-01-01 00:00:00
1,2,44,Germany,Instagram,205,Reels,7.46,7,2023-01-01 01:00:00
2,3,30,UK,X,63,Live,2.86,6,2023-01-01 02:00:00

In [5]:
df.tail(3)

,user_id,age,country,platform,daily_usage_minutes,content_type,engagement_score,mental_fatigue_level,date
4997,4998,37,Germany,Instagram,203,Shorts,7.28,5,2023-07-28 05:00:00
4998,4999,31,India,Instagram,151,Live,1.21,8,2023-07-28 06:00:00
4999,5000,56,India,Instagram,110,Reels,5.09,9,2023-07-28 07:00:00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               5000 non-null   int64
 1   age                   5000 non-null   int64
 2   country               5000 non-null   object
 3   platform              5000 non-null   object
 4   daily_usage_minutes   5000 non-null   int64
 5   content_type          5000 non-null   object
 6   engagement_score      5000 non-null   float64
 7   mental_fatigue_level  5000 non-null   int64
 8   date                  5000 non-null   object
dtypes: float64(1), int64(4), object(4)
memory usage: 351.7+ KB